version: 2 
jobs:
  build:
    working_directory: ~/profsend-v2
    docker: # Docker 

      - image: circleci/node:8.12.0
      - image: mongo:3.4.4 
    steps: 
      - checkout 
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-package
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: test
          command: npm run test
      - run: 
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results: 
          path: test-results.xml