name: Vulnerability check

on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-18.04
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with: 
          node-version: "${{ matrix.node-version }}"
      - 
        name: "Vulnerability check now"
        run: "npm install"
      - 
        env: 
          CI: true
        name: "repositry push"
        run: |
            git config user.name "gumieprof-CI"
            git config user.email "gutsmine910@gmail.com"
            git remote set-url origin https://gumieprof:${{ secrets.GITHUB_PASS }}@github.com/gumieProf/profsend
            git branch
            git checkout main
            git branch
            date >> CItime.md
            git add .
            git commit -m "[CI]Vulnerability check"
            git push origin main
